'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query(`
      INSERT INTO
        posts(title, category, content, cover, user_id, created_at, updated_at)
      VALUES
      ('Andalax', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',1, '2019-01-08', '2019-01-08'),
    ('Aerified', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',2, '2019-01-08', '2019-01-08'),
    ('Flowdesk', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Tampflex', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Zamit', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',1, '2019-01-08', '2019-01-08'),
    ('Toughjoyfax', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',2, '2019-01-08', '2019-01-08'),
    ('Gembucket', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Bigtax', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/cc0000/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Lotstring', 'software','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Zathin', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',2, '2019-01-08', '2019-01-08'),
    ('Redhold', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/ff4444/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Tresom', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',2, '2019-01-08', '2019-01-08'),
    ('Veribet', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.png/ff4444/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Stronghold', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',2, '2019-01-08', '2019-01-08'),
    ('Hatity', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/cc0000/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Overhold', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Regrant', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.png/5fa2dd/ffffff',2, '2019-01-08', '2019-01-08'),
    ('Tresom', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',1, '2019-01-08', '2019-01-08'),
    ('Bytecard', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/ff4444/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Temp', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/5fa2dd/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Alpha', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',1, '2019-01-08', '2019-01-08'),
    ('Vagram', 'cloud','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Ventosanzap', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Konklux', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Viva', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Konklux', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Zoolab', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/5fa2dd/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Zamit', 'security','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Ventosanzap', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/ff4444/ffffff',1, '2019-01-08', '2019-01-08'),
    ('Duobam', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Voltsillam', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Fix San', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Matsoft', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Konklab', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Aerified', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.png/5fa2dd/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Overhold', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Overhold', 'testing','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Bigtax', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/cc0000/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Sonsing', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Viva', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/dddddd/000000',3, '2019-01-08', '2019-01-08'),
    ('Cookley', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/ff4444/ffffff',3, '2019-01-08', '2019-01-08'),
    ('Fixflex', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Fix San', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Flowdesk', 'network','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
'http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Stim', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Bamity', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/5fa2dd/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Quo Lux', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/dddddd/000000',4, '2019-01-08', '2019-01-08'),
    ('Mat Lam Tam', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Aerified', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.jpg/cc0000/ffffff',4, '2019-01-08', '2019-01-08'),
    ('Ventosanzap', 'AI','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.','http://dummyimage.com/1920x1080.bmp/5fa2dd/ffffff',4, '2019-01-08', '2019-01-08');`);
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
